from __future__ import annotations

import time
from typing import Any, Dict, List, Optional

import httpx

from ..config import settings


class ProkeralaClient:
    def __init__(self, client_id: str, client_secret: str, base_url: str = "https://api.prokerala.com/v2"):
        self.client_id = client_id
        self.client_secret = client_secret
        self.base_url = base_url.rstrip("/")
        self._token: Optional[str] = None
        self._token_exp: float = 0.0
        self._auth_base = "https://api.prokerala.com"
        self._session = httpx.Client(timeout=30)

    def _get_token(self) -> str:
        now = time.time()
        if self._token and now < self._token_exp - 30:
            return self._token
        resp = httpx.post(
            f"{self._auth_base}/token",
            data={
                "grant_type": "client_credentials",
                "client_id": self.client_id,
                "client_secret": self.client_secret,
            },
            timeout=30,
        )
        resp.raise_for_status()
        data = resp.json()
        self._token = data["access_token"]
        self._token_exp = now + float(data.get("expires_in", 3600))
        return self._token

    def _auth_headers(self) -> Dict[str, str]:
        return {"Authorization": f"Bearer {self._get_token()}"}

    def get(self, path: str, params: Dict[str, Any]) -> Dict[str, Any]:
        url = f"{self.base_url}{path}"
        r = self._session.get(url, params=params, headers=self._auth_headers())
        r.raise_for_status()
        return r.json()

    def get_pdf(self, path: str, params: Dict[str, Any]) -> bytes:
        url = f"{self.base_url}{path}"
        headers = self._auth_headers() | {"Accept": "application/pdf"}
        r = self._session.get(url, params=params, headers=headers)
        r.raise_for_status()
        return r.content


class AstrologyProvider:
    def __init__(self, client: Optional[ProkeralaClient] = None):
        if client is None:
            if not settings.prokerala_client_id or not settings.prokerala_client_secret:
                raise RuntimeError("PROKERALA_CLIENT_ID/SECRET not configured")
            client = ProkeralaClient(
                client_id=settings.prokerala_client_id,
                client_secret=settings.prokerala_client_secret,
                base_url=settings.prokerala_base_url,
            )
        self.client = client

    def kundli_advanced(self, coordinates: str, dt_iso: str, ayanamsa: int = 1, la: str = "en") -> Dict[str, Any]:
        return self.client.get(
            "/astrology/kundli/advanced",
            {
                "coordinates": coordinates,
                "datetime": dt_iso,
                "ayanamsa": ayanamsa,
                "la": la,
            },
        )

    def kundli_basic(self, coordinates: str, dt_iso: str, ayanamsa: int = 1, la: str = "en") -> Dict[str, Any]:
        return self.client.get(
            "/astrology/kundli",
            {
                "coordinates": coordinates,
                "datetime": dt_iso,
                "ayanamsa": ayanamsa,
                "la": la,
            },
        )

    def divisional(self, coordinates: str, dt_iso: str, chart_type: str, ayanamsa: int = 1, la: str = "en") -> Dict[str, Any]:
        return self.client.get(
            "/astrology/divisional-planet-position",
            {
                "coordinates": coordinates,
                "datetime": dt_iso,
                "chart_type": chart_type,
                "ayanamsa": ayanamsa,
                "la": la,
            },
        )

    def transit_planet_position(self, coordinates: str, transit_dt_iso: str, house_system: int = 2, ayanamsa: int = 1) -> Dict[str, Any]:
        return self.client.get(
            "/astrology/transit-planet-position",
            {
                "current_coordinates": coordinates,
                "transit_datetime": transit_dt_iso,
                "house_system": house_system,
                "ayanamsa": ayanamsa,
            },
        )

    def shadbala_pdf(self, first_name: str, gender: str, coordinates: str, dt_iso: str, place: str, la: str = "en") -> bytes:
        # Build query params according to openapi: input[...] and options[...] deep object
        params: Dict[str, Any] = {
            "input[first_name]": first_name,
            "input[gender]": gender,
            "input[datetime]": dt_iso,
            "input[coordinates]": coordinates,
            "input[place]": place,
            "options[modules][0][name]": "shadbala-table",
            "options[modules][0][options]": "{}",
            "options[template][style]": "basic",
            "options[template][footer]": "Generated by Parasara Hora AI",
            "options[report][name]": "Shadbala Table",
            "options[report][caption]": "Planetary Strengths",
            "options[report][brand_name]": "Parasara Hora AI",
            "options[report][la]": la,
        }
        return self.client.get_pdf("/report/personal-reading/instant", params)
